sudo: required
services:
  - docker

before_install:
  - docker-compose up -d

# script:
#   - docker run -e CI=true ssedaghati/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-579311538689"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"